name: Enhanced CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint
        run: flake8 src/ tests/ || true  # Lint may have platform issues
      - name: Test
        run: pytest --cov=src
  
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install safety
        run: pip install safety
      - name: Dependency vulnerability check
        run: safety check
      - name: Security scanning
        run: pip install bandit && bandit -r src/
  
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t aisis .
  
  # TODO: GPU testing - requires self-hosted runner with GPU
  # TODO: Performance benchmarking - add script to run benchmarks
